### ISSUE TITLE
Ingress Secret is not getting the Keys values

### ISSUE THREAD

**Issue by raefezzeldin** [sushilkm/nifi-chart#10]
I am using the following configuration for Ingress:

```

ingress:
  enabled: true
  affinity: "cookie"
  affinityMode: "affinityMode"
  tlsVerifyDepth: 1
  user:
    name: "CN=proxyUser"
  tlsOnAnonymousNifi: true
  authenticateIngressOnAnonymousNifi: true
  tlsCerts:
    dir: "/opt/nifi/nifi-current/config-data/certs/proxy"
    privateKey: key.pem
    certificate: crt.pem
    rootCaCertificate: ca-crt.pem
  

```

The UI appeared but it isnot secured over HTTPS connection the reason is that the ingress I am using the data part is empty.
